
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compiladores1.appcliente.analizadores.json;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDD = 21;
  public static final int CORCHETEC = 8;
  public static final int METODOS = 14;
  public static final int CORCHETEA = 7;
  public static final int DECIMAL = 5;
  public static final int ALGO = 22;
  public static final int SCORE = 11;
  public static final int LLAVEC = 10;
  public static final int LLAVEA = 9;
  public static final int COMILLAS = 6;
  public static final int PARAMTETROS = 19;
  public static final int TIPO = 17;
  public static final int COMA = 3;
  public static final int COMENTARIOS = 15;
  public static final int DOSPUNTO = 2;
  public static final int NOMBRE = 18;
  public static final int EOF = 0;
  public static final int TEXTO = 20;
  public static final int error = 1;
  public static final int CLASES = 12;
  public static final int ENTERO = 4;
  public static final int VARIBALES = 13;
  public static final int FUNCION = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOSPUNTO",
  "COMA",
  "ENTERO",
  "DECIMAL",
  "COMILLAS",
  "CORCHETEA",
  "CORCHETEC",
  "LLAVEA",
  "LLAVEC",
  "SCORE",
  "CLASES",
  "VARIBALES",
  "METODOS",
  "COMENTARIOS",
  "FUNCION",
  "TIPO",
  "NOMBRE",
  "PARAMTETROS",
  "TEXTO",
  "IDD",
  "ALGO"
  };
}

